version: 0.1

environment_variables:
  plaintext:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
phases:
  install:
    commands:
      - yum update -y
      - yum install -y util-linux autotools automake rpm-build rpm-sign expect tree
  pre_build:
    commands:
      - aws s3 cp s3://openbedrock/gnupg.tar.gz /root/
      - cd /root && tar xfvz gnupg.tar.gz
      - mkdir /root/rpmbuild
      - echo -e "%_topdir /root/rpmbuild\n%_gpg_name OpenBedrock" > /root/.rpmmacros
  build:
    commands:
      - env
      - automake --version
      - autoreconf -i --force
      - ./configure --prefix=/usr --with-perl5libdir --enable-rpmbuild --disable-perldeps
      - chmod +x bin/splice-in-file
      - make dist
      - echo $(basename $(ls -1 *.tar.gz | head -1) .tar.gz) > package-name
      - rpmbuild -tb $(ls -1 *.tar.gz | head -1)
      - mkdir /root/repo
      - find ~/rpmbuild/RPMS/ -name '*.rpm' | sed 's|/root/rpmbuild/RPMS/||' > "/root/repo/$(cat package-name).lst"
      - test -e target-repo && echo "YRB_EXTRA=\"$CODEBUILD_WEBHOOK_HEAD_REF|$CODEBUILD_SOURCE_REPO_URL\"" >> target-repo
      - cp target-repo "/root/repo/$(cat package-name).repo"
      - tree /root
      - cat /root/repo/$(cat package-name).lst
artifacts:
  discard-paths: yes
  files:
    - /root/rpmbuild/RPMS/**/*
    - /root/repo/*
