#!/bin/bash

[ ! -e bedrock-build ] && echo "0" > bedrock-build

BEDROCK_RELEASE=$(cat bedrock-build)

case "$1" in
    release) 
	BEDROCK_RELEASE="0"
	;;
    
    minor)
	BEDROCK_RELEASE=$(expr 1 + $BEDROCK_RELEASE)
	;;
    
    *)
	if autoreconf -i --force; then 
	    ./configure --prefix=/usr && make dist
	    
 # get last tar ball built
	    bedrock=$(ls -1t bedrock-*.tar.gz | head -n 1)

 # build RPM
	    rpmbuild -tb $bedrock
	else
	    echo "Build failed: $@" > 2
	    exit -1
	fi

esac

version=$(perl -n -e '/^ac_init(.*?)(\d\.\d\.\d+)/i && print "$2\n";' configure.ac)

echo "bedrock-$version-$BEDROCK_RELEASE"
echo "$BEDROCK_RELEASE" > bedrock-build

