#!/bin/bash
# -*- mode: sh; -*-

set -ex
./bootstrap
./configure
make
cd src/main/perl
make test
cd -
cd src/main/perl/lib
make test
cd -
./build build
cd cpan
PERL5LIB=/usr/local/share/perl5 make cpan
cd -
# check to see if we have a tarbar, a CPAN distribution and the rpm
# file
tarball=$(ls -1t bedrock*.tar.gz | head -1)
test -n $tarball && test -f $tarball || false
cpandist=$(ls -1t cpan/Bedrock*.tar.gz | head -1)
test -n $cpandist && test -f $cpandist || false
rpm=$(ls -1t $HOME/rpmbuild/RPMS/noarch/bedrock-core*rpm | head -1)
test -n $rpm && test -f $rpm || false
