#!/bin/bash
# -*- mode: sh; -*-

set -ex

if ! test -e bootstrap; then
    if ! test -d openbedrock; then
        git clone https://github.com/rlauer6/openbedrock.git
    fi
    cd openbedrock
    workdir=$(pwd)
    
    if test -n "$1"; then
        git checkout "$1"
    fi
else
    workdir=$(pwd)
fi

echo $workdir

./bootstrap && ./configure && make

########################################################################
# run tag tests
########################################################################
cd src/main/perl
make test

########################################################################
# run lib tests
########################################################################
cd $workdir
cd src/main/perl/lib
make test

########################################################################
# run build to create rpms and distribution tarball
########################################################################
cd $workdir 
./build build

########################################################################
# create a CPAN distribution tarball
########################################################################
cd $workdir
cd cpan
PERL5LIB=/usr/lib/bedrock/perl5 make cpan

########################################################################
# create a CPAN distribution tarball for `Bedrock::Lite`
########################################################################
cd $workdir
cd cpan/bedrock-lite
PERL5LIB=/usr/lib/bedrock/perl5 make cpan

########################################################################
# check for tarbar, CPAN distribution, rpm files
########################################################################
cd $workdir 
tarball=$(ls -1t bedrock*.tar.gz | head -1)
test -n $tarball && test -f $tarball || false

cpandist=$(ls -1t cpan/Bedrock*.tar.gz | head -1)
test -n $cpandist && test -f $cpandist || false

cpandist=$(ls -1t cpan/bedrock-lite/Bedrock-Lite-*.tar.gz | head -1)
test -n $cpandist && test -f $cpandist || false

rpm=$(ls -1t $HOME/rpmbuild/RPMS/noarch/bedrock-core*rpm | head -1)
test -n $rpm && test -f $rpm || false
