version: 0.1

environment_variables:
  plaintext:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
phases:
  install:
    commands:
      - yum update -y
      - yum install -y util-linux rpm-build rpm-sign wget expect aws-cli createrepo
  build:
    commands:
      - build build -r -x
artifacts:
  files:
    - /root/rpmbuild/RPMS/noarch/*
  discard-paths: yes

