version: 0.1

environment_variables:
  plaintext:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
phases:
  install:
    commands:
      - yum update -y
      - yum install -y util-linux rpm-build rpm-sign wget expect aws-cli createrepo
  build:
    commands:
      - aws s3 cp s3://openbedrock/gnupg.tar.gz /root/
      - cd /root && tar xfvz gnupg.tar.gz
      - mkdir /root/rpmbuild
      - echo -e "%_topdir /root/rpmbuild\n%_gpg_name OpenBedrock" > /root/.rpmmacros
      - ./build build -r -x
      - ./build deploy
