version: 0.1

environment_variables:
  plaintext:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
phases:
  install:
    commands:
      - yum update -y
      - yum install -y util-linux rpm-build rpm-sign wget expect aws-cli createrepo
      - aws s3 cp s3://openbedrock/gnupg.tar.gz /root/
      - cd /root && tar xfvz gnupg.tar.gz && cp /root/rpm-sign $CODEBUILD_SRC_DIR/
      - echo -e "%_topdir /root/rpmbuild\n%_gpg_name OpenBedrock" > /root/.rpmmacros
  build:
    commands:
      - ./build build -r -x
      - 'for a in $(ls -1 /root/rpmbuild/RPMS/noarch/*.rpm); do /root/rpm-sign OpenBedrock OpenBedrock "$a"; done'
      - ./build createrepo -b /root/yum-repo
artifacts:
  files:
    - "**/*"
  base-directory:
    - /root/yum-repo

