#!/usr/bin/env bash
#-*- mode: sh; -*-

set -oue pipefail

make maintainer-clean
./bootstrap && ./configure
make clean && make

########################################################################
# create & install Bedrock-Core
########################################################################
cd cpan/bedrock-core
rm -f *.tar.gz
make cpan
cpanm -n -l $HOME Bedrock*.tar.gz

########################################################################
# create & install Bedrock
########################################################################
cd ..
rm -f *.tar.gz
make cpan
cpanm -n -l $HOME Bedrock*.tar.gz

