# ident "@(#) $Header$"
# ident "@(#)        $Name$"
#
# Name of Release: $Name$
# $Log$
# Revision 1.1  2000/12/18 18:00:50  sridhar
# Moved Bedrock::SIS::Base::Shell to Bedrock::Context::Shell
#
#

include ../make.pre

     CURRENT_PATH = Context

          TARGETS = Shell.pm

all: $(TARGETS)

install:: $(TARGETS:%=%-install)

include ../make.post
