#!/bin/bash

echo -e "[bedrock]\nname=bedrock\ngpgcheck=0\nbaseurl=http://openbedrock-repo.s3-website-us-east-1.amazonaws.com\n" > /etc/yum.repos.d/bedrock.repo
yum update -y
yum install -y bedrock-openbedrock
service httpd restart
chkconfig httpd on

