#!/bin/bash

# create a temporary repo
repo=$(mktemp -d)
mkdir ${repo}/noarch
BUCKET=openbedrock-repo

# if we successfully built some RPMs, create a temporary repo and sync
# with AWS S3 repo
if test -e "$1"; then
    cp "$1" ${repo}/noarch
    
# get all the .rpm files from the S3 bucket and recreate the repo
    createrepo $repo

# sync local repo with S3 bucket, make it PUBLIC
    PERMISSION="--grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers"
    aws s3 sync --recursive --include="*" ${repo} s3://$BUCKET/ $PERMISSION
    aws s3 ls s3://$BUCKET/
# cleanup local copy of repo
    rm -rf $repo
fi
