#!/bin/bash

# run Bedrock tag tests
TESTS="$(cat $1)"
SRC=$(realpath $2)
BUILD=$(realpath $3)

test_dir=$(mktemp -d)
mkdir $test_dir/t

for a in $TESTS; do 
    test_file=$(basename $a .yml)
    ln -s $SRC/test-tag.pl ${test_dir}/t/${test_file}.t
    test -e $test_dir/t/$test_file.t || exit 1;
done

if test -z "$DBI_SOCKET"; then
    if test -e '/tmp/mysqld/mysqld.sock'; then 
	DBI_SOCKET=/tmp/mysqld/mysqld.sock
    fi
fi

CONFIG_PATH="$SRC/t/config:.:$BUILD/../bedrock/config"
PERL5LIB=""
TEST_PATH="$SRC"
/usr/local/bin/prove -v -I "$BUILD/lib" -I "$BUILD/lib/Bedrock" -I "$BUILD/lib/Bedrock/Text" "$test_dir/t"
test -n "$test_dir" && rm -rf "$test_dir" 2>/dev/null || true
rm -f foo.roc foo.inc foo.csv 2>/dev/null || true
for a in $(ls $BUILD/bedrock-*.log 2>/dev/null | grep -v bedrock-test.log); do \
    rm -f $a || true; \
done
