#!/usr/bin/env bash
#-*- mode: sh; -*-

########################################################################
cleanup() {
########################################################################
    rm -f foo.roc foo.inc foo.csv 2>/dev/null || true
    
    for a in $(ls $BUILD/bedrock-*.log 2>/dev/null | grep -v bedrock-test.log); do
        rm -f $a || true
    done

    test -n "$test_dir" && rm -rf "$test_dir" 2>/dev/null;
}

########################################################################
# MAIN SCRIPT STARTS HERE
########################################################################

set -oue pipefail
trap cleanup EXIT

# run Bedrock tag tests
TESTS="$(cat $1)"
SRC=$(realpath $2)
BUILD=$(realpath $3)

test_dir=$(mktemp -d)
mkdir $test_dir/t

for a in $TESTS; do 
    test_file=$(basename $a .yml)
    ln -s $SRC/t/$(basename $a) ${test_dir}/t/${test_file}.yml
    ln -s $SRC/bin/bedrock-runner.pl ${test_dir}/t/${test_file}.t
    test -e $test_dir/t/$test_file.t || exit 1;
done

SOCKET_PATH="${SOCKET_PATH:-/tmp/mysqld/mysqld.sock}"
DBI_SOCKET="${DBI_SOCKET:-}"

if test -z "$DBI_SOCKET"; then
    if test -e "$SOCKET_PATH"; then 
        export DBI_SOCKET=$SOCKET_PATH
    fi
fi

PROVE="$(command -v prove)"
if test -z "$PROVE"; then
    echo "ERROR: could not find 'prove'"
    exit 1
fi

BEDROCK_CONFIG_PATH="$SRC/t/config" \
$PROVE -v -I "$BUILD/lib" -I "$BUILD/lib/Bedrock" -I "$BUILD/lib/Bedrock/Text" "$test_dir/t"

exit 0
