#!/usr/bin/env bash
#-*- mode: sh; -*-

########################################################################
cleanup() {
########################################################################
    rm -f foo.roc foo.inc foo.csv 2>/dev/null || true
    
    for a in $(ls $BUILD/bedrock-*.log 2>/dev/null | grep -v bedrock-test.log); do
        rm -f $a || true
    done

    test -n "$test_dir" && rm -rf "$test_dir" 2>/dev/null;
}

########################################################################
# main script starts here
########################################################################

# run Bedrock tag tests
TESTS="$(cat $1)"
SRC=$(realpath $2)
BUILD=$(realpath $3)

test_dir=$(mktemp -d)
mkdir $test_dir/t

for a in $TESTS; do 
    test_file=$(basename $a .yml)
    ln -s $SRC/test-tag.pl ${test_dir}/t/${test_file}.t
    test -e $test_dir/t/$test_file.t || exit 1;
done

SOCKET_PATH=/tmp/mysqld/mysqld.sock

if test -z "$DBI_SOCKET"; then
    if test -e "$SOCKET_PATH"; then 
        export DBI_SOCKET=$SOCKET_PATH
    fi
fi

CONFIG_PATH="$SRC/t/config:.:$BUILD/../bedrock/config"
TEST_PATH="$SRC"
PROVE=$(command -v prove)

$PROVE -v -I "$BUILD/lib" -I "$BUILD/lib/Bedrock" -I "$BUILD/lib/Bedrock/Text" "$test_dir/t"

cleanup

exit 0
