#!/usr/bin/env  bash
# -*- mode:sh -*-

PROFILE=""

for a in $@; do 
  PROFILE="$PROFILE --profile $a"
done

sudo systemctl stop mysql
sudo systemctl stop apache2 
sudo systemctl stop redis 

BEDROCK="$(pwd)/.." docker compose $PROFILE up

