

version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bedrock'
      MYSQL_USER: 'fred'
      MYSQL_PASSWORD: 'flintstone'      # Password for root access
      MYSQL_ROOT_PASSWORD: 'bedrock'
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - /tmp/mysqld:/var/run/mysqld
  web:
    read_only: false
    build:
      context: ${BEDROCK:?set BEDROCK}/docker
      dockerfile: ${PWD}/Dockerfile
    image: "bedrock:latest"
    ports:
      - '80:80'
    entrypoint: ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
    volumes:
      - ${HOME:?set HOME}/data:/var/www/data
      - ${HOME:?set HOME}/www/log:/var/www/log
      - ${HOME:?set HOME}/www/html:/var/www/html
      - ${HOME:?set HOME}/www/include:/var/www/include
      - ${HOME:?set HOME}/www/session:/var/www/session
volumes:
  my-db:
