FROM amazonlinux:2

ADD bedrock.repo /etc/yum.repos.d/bedrock.repo
ADD perl-aws.repo /etc/yum.repos.d/perl-aws.repo
RUN amazon-linux-extras install epel -y

# Perl dependencies
RUN yum install -y perl-core

# Apache
RUN yum install -y httpd mod_perl

# Extras
RUN yum install -y mariadb less tree gcc procps curl make iputils

# cpanm
RUN curl -L https://cpanmin.us | perl - App::cpanminus

# cleanup 
RUN yum clean all && rm -rf /var/cache/yum

CMD /usr/sbin/apachectl -D FOREGROUND
