version: "3.9"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    hostname: s3
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
          - net-amazon-s3-test-test.localhost.localstack.cloud
            #    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3,ssm,secretsmanager,sqs
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  redis:
    image: redis/redis-stack-server:latest
    ports: 
      - '6379:6379'
    expose:
      - 6379
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bedrock'
      MYSQL_USER: 'fred'
      MYSQL_PASSWORD: 'flintstone'      # Password for root access
      MYSQL_ROOT_PASSWORD: 'bedrock'
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - /tmp/mysqld:/var/run/mysqld
  web:
    read_only: false
    build:
      context: ${BEDROCK:?set BEDROCK}/docker
      dockerfile: ${PWD}/Dockerfile
    image: "bedrock:latest"
    ports:
      - '80:80'
    entrypoint: ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
    volumes:
      - ${HOME:?set HOME}/git/openbedrock/docker/perl_bedrock.conf:/etc/httpd/conf.d/perl_bedrock.conf
      - ${HOME:?set HOME}/git/openbedrock/docker/httpd.conf:/etc/httpd/conf/httpd.conf
      - ${HOME:?set HOME}/git/openbedrock/docker/mysql-session.xml:/usr/lib/bedrock/config.d/startup/mysql-session.xml
      - ${HOME:?set HOME}/git/openbedrock/docker/data-sources.xml:/usr/lib/bedrock/config/data-sources.xml
      - ${HOME:?set HOME}/git/openbedrock/docker/tagx.xml:/usr/lib/bedrock/config/tagx.xml
      - ${HOME:?set HOME}/git/openbedrock/docker/log4perl.conf:/usr/lib/bedrock/config/log4perl.conf
      - ${HOME:?set HOME}/git/openbedrock/docker/pod_paths.xml:/usr/lib/bedrock/config/pod_paths.xml
      - ${HOME:?set HOME}/git/openbedrock/docker/markdown_paths.xml:/usr/lib/bedrock/config/markdown_paths.xml
      - ${HOME:?set HOME}/www:/var/www
      - ${HOME:?set HOME}/git/tb-www:/tb-www
      - ${HOME:?set HOME}/git/openbedrock:/openbedrock
      - ${HOME:?set HOME}/git/tb-www-website:/tb-www-website
      - ${HOME:?set HOME}/git/tb-dev:/tb-dev
      - ${HOME:?set HOME}/git/terraform:/terraform
      - ${HOME:?set HOME}/git/tbc-codebuild:/tbc-codebuild
      - ${HOME:?set HOME}/git/yum-repo-updater:/yum-repo-updater
      - ${HOME:?set HOME}/git/perl-aws-repo:/perl-aws-repo
      
volumes:
  my-db:


