FROM bedrock-base-al2023 AS bedrock-al2023

COPY Bedrock.tar.gz .

# Bedrock
RUN cpanm -n -v Bedrock.tar.gz

RUN bedrock-site-install --distro=redhat

# cleanup 
RUN dnf clean all && rm -rf /var/cache/yum
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
