version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bedrock'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'fred'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'flintstone'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'bedrock'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
    read_only: false
    build:
      context: ${BEDROCK:?set BEDROCK}/docker
      dockerfile: ${PWD}/Dockerfile
    image: "bedrock:latest"
    ports:
      - '80:80'
    entrypoint: ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
    volumes:
      - ${HOME:?set HOME}/data:/var/www/data
      - ${HOME:?set HOME}/www/log:/var/www/log
      - ${HOME:?set HOME}/www/html:/var/www/html
      - ${HOME:?set HOME}/www/include:/var/www/include
      - ${HOME:?set HOME}/www/session:/var/www/session
volumes:
  my-db:
  
