FROM bedrock-al2023-base AS bedrock-al2023

ARG VERSION

COPY Bedrock-Core-$VERSION.tar.gz .
RUN cpanm -n -v Bedrock-Core-$VERSION.tar.gz

COPY Bedrock-$VERSION.tar.gz .
RUN cpanm -n -v Bedrock-$VERSION.tar.gz

RUN bedrock-site-install --distro=redhat

# cleanup 
RUN dnf clean all && rm -rf /var/cache/yum

COPY setup.sql /usr/local/share/setup.sql

COPY start-server /usr/local/bin/start-server

CMD /usr/local/bin/start-server
