#!/bin/bash
# -*- mode: sh; -*-

DOCKER_CONTAINER_ID=$(docker ps -a | grep mysql | awk '{print $1}')
test -n "$DOCKER_CONTAINER_ID" && docker stop $DOCKER_CONTAINER_ID && docker rm $DOCKER_CONTAINER_ID

