#!/bin/bash
# -*- mode: sh; -*-

trap 'test -e "$create_db" && rm -f "$create_db"' EXIT

# usage: mysql-up tag

MYSQL_VERSION="$1"
MYSQL_VERSION=${MYSQL_VERSION:-latest}

if [ "$MYSQL_VERSION" = "latest" ]; then
    NATIVE_PASSORD="--default-authentication-plugin=mysql_native_password"
fi

create_db=$(mktemp)

cat >$create_db <<EOF
drop database if exists bedrock;

create database bedrock;

drop user if exists fred;

create user 'fred'@'%' identified by 'flintstone';

grant all privileges on *.* to 'fred'@'%';

use bedrock;

create table session
 (
  id           int(11)      not null auto_increment primary key,
  session      varchar(50)  default null,
  login_cookie varchar(50)  not null default '',
  username     varchar(50)  not null default '',
  password     varchar(64)  default null,
  firstname    varchar(30)  default null,
  lastname     varchar(50)  default null,
  email        varchar(100) default null,
  prefs        text,
  updated      timestamp    not null default current_timestamp on update current_timestamp,
  added        datetime     default null,
  expires      datetime     default null
);
EOF

PASSWORD=bedrock
USER=root

export DOCKER_CONTAINER_ID=$(docker run -e MYSQL_ROOT_PASSWORD=$PASSWORD -d mysql:$MYSQL_VERSION $NATIVE_PASSWORD)
export DBI_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DOCKER_CONTAINER_ID)

n=0

while  ! mysqladmin ping -u $USER --password=$PASSWORD -h $DBI_HOST 2>/dev/null; do
      printf "...waiting for MySQL..%d\r" $n
      sleep 2;
      n=$((n + 1))
done
      
cat $create_db | mysql -u $USER --password=$PASSWORD -h $DBI_HOST

echo "describe session" | mysql -u $USER --password=$PASSWORD -h $DBI_HOST bedrock
