#!/usr/bin/env bash
#-*- mode: sh; -*-

# configure with --disable-database to prevent default assignment of a root password
if test -n "$MYSQL_ROOT_PASSWORD"; then

    until mysql -h $MYSQL_HOST -u root --password="$MYSQL_ROOT_PASSWORD" -e "SELECT 1" >/dev/null; do
        echo "Waiting for MySQL to be ready..."
        sleep 2
    done

    if test -e /usr/local/share/setup.sql; then
        mysql -h $MYSQL_HOST -u root -p"$MYSQL_ROOT_PASSWORD" < /usr/local/share/setup.sql
    fi
fi

source /etc/os-release

echo "Starting Apache..."

if test "$ID" = "debian"; then
  source /etc/apache2/envvars

  exec /usr/sbin/apache2 -k start -D FOREGROUND
else
  exec /usr/sbin/httpd -DFOREGROUND
fi
