#!/usr/bin/env perl

use strict;
use warnings;

use Test::More;
use Test::Output;
use Cwd;
use Bedrock::Constants qw(:chars);
use Data::Dumper;
use English qw(-no_match_vars);
use Bedrock::Service qw(:all);

BEGIN {
  $ENV{GATEWAY_INTERFACE} = 'CGI/1.1';
  # Ensure we don't accidentally trigger Apache behavior in tests
  delete $ENV{SERVER_SOFTWARE};
}

use_ok('Bedrock::BedrockCGI');

########################################################################
# print
########################################################################
subtest 'print' => sub {
  my $cgi = Bedrock::CGI->new;

  stdout_like(
    sub {
      $cgi->print('<p>test</p>');
      $cgi->flush_output;
    },
    # generated by CGI.pm when running outside of Apache.
    qr/\A(?:HTTP\/1\.0\s+\d+\s+.*?\r\n)?Content-type:\s+text\/html\r\n\r\n<p>test<\/p>\z/xsmi,
    'print',
  );
};

########################################################################
# output
########################################################################
subtest 'output' => sub {
  my $output = $EMPTY;

  open my $fh, '>', \$output
    or BAIL_OUT('ERROR: could not open scalar ref for reading.');

  $fh->autoflush;

  my $cgi = Bedrock::CGI->new( output_handle => $fh, autoflush => 1 );

  my $html = element( element_start( div => style( $main::FONT_SIZE, $PURPLE, $BOLD, $MARGIN ) ), 'foo' );
  $cgi->print("$html\n");

  my $pre = element( pre => 'foo' );
  $html = "$html\n$pre\n";

  $cgi->print( sprintf "%s\n", $pre );

  $cgi->flush_output;

  $fh->close;

  # allow for the Status Line prefix here as well.
  like( $output, qr/\A(?:HTTP\/1\.0\s+\d+\s+.*?\r\n)?Content.*<div.*<\/pre>\n\z/xsm, 'content' );
};

done_testing;

1;
