#!/usr/bin/env perl

use strict;
use warnings;

use lib qw{.};

use Bedrock::Constants qw{:chars};
use Data::Dumper;
use English qw{-no_match_vars};
use Test::More;
use Test::Utils qw{:all};

our %TESTS = fetch_test_descriptions(*DATA);  # from Test::Utils

########################################################################

plan tests => 1 + keys %TESTS;

use_ok('');

########################################################################
subtest 'test' => sub {
########################################################################
  ok(1);

  diag( Dumper( [] ) );
};
########################################################################
subtest 'test1' => sub {
########################################################################
  ok(1);

  diag( Dumper( [] ) );
};
########################################################################
subtest 'test2' => sub {
########################################################################
  ok(1);

  diag( Dumper( [] ) );
};

1;

__DATA__
test => test
test1 => test
test2 => test
END_OF_PLAN  
