# ident "@(#) $Header$"
# ident "@(#)        $Name$"
# 
# $Log$
# Revision 1.1  2000/02/04 20:44:58  sridhar
# Makefile for build/install perl modules
#
# 

include ../../make.pre

     CURRENT_PATH = SIS/Base

          TARGETS = 

all:

install:

include ../../make.post
