<div class="accordion accordion-flush" id="plugins-content">

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#application-plugins" aria-expanded="false" aria-controls="application-plugins">
        Application Plugins
      </button>
    </h2>

    <div id="application-plugins" class="accordion-collapse collapse" data-bs-parent="#plugins-content">
      <div class="accordion-body">
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#filters" aria-expanded="false" aria-controls="filters">
        Filters
      </button>
    </h2>

    <div id="filters" class="accordion-collapse collapse" data-bs-parent="#plugins-content">
      <div class="accordion-body">
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#plugins" aria-expanded="false" aria-controls="plugins">
        Plugins
      </button>
    </h2>

    <div id="plugins" class="accordion-collapse collapse" data-bs-parent="#plugins-content">
      <div class="accordion-body">
      </div>
    </div>
  </div>

</div>
