# ident "@(#) $Header$"
# ident "@(#)        $Name$"
# 
# $Log$
# Revision 1.5  2000/09/18 14:19:28  sridhar
# Moved Perl/Text to Perl/Bedrock/Text
#
# Revision 1.4  2000/09/15 14:27:23  sridhar
# Adding Bedrock/Makefile
#
#

include ../make.pre

     CURRENT_PATH = Bedrock

          TARGETS = 

all:
	cd PDF		&& $(MAKE) $@
	cd Text		&& $(MAKE) $@

install:
	cd PDF		&& $(MAKE) $@
	cd Text		&& $(MAKE) $@

include ../make.post
