# ident "@(#) $Header$"
# ident "@(#)        $Name$"
# 
# $Log$
# Revision 1.1  2000/02/08 15:25:04  sridhar
# Added TagX
#
# 

include ../../../../../make.pre

     CURRENT_PATH = Text/TagX/TAG/WithBody/If

          TARGETS = Else.pm

all:
	$(PERL) $(PERLINCLUDES) $(PERLFLAGS) Else.pm

install:
	$(INSTALL) Else.pm		$(CURRENT_TARGET)

include ../../../../../make.post
