<var $head>
  <hr/>
  <var $tags>
  <hr/>

  <h1>System Documentation</h1>
  <var $system_docs>

  <hr/>
  <h1>User Documentation</h1>
  <var $user_docs>
  <hr/>

  <h1>Additional Documentation</h1>
  <var $markdown_docs>

  <hr/>
  <h1>Bedrock Environment</h1>
  <var $bedrock_env>


  <h1>Bedock Internal Documentation</h1>
  <var $bedrock_internal_docs>
  <hr/>

  <h1 id="log4perl-container">Bedrock Log Configuration</h1>
  <h2><var $config.LOG4PERL></h2>
  <pre style="display:none;"><var $log4perl></pre>
  <script>
    
  </script>
  </body>
</html>
