name: openbedrock
on: 
  push:
    branches: "*"
jobs:
  test-module:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rlauer6/test_5.36.0:latest
      credentials:
        username: rlauer6
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/rlauer6/test_5.36.0:latest
          options: -v ${{github.workspace}}:/codebase
          run: |
            amazon-linux-extras install epel
            yum install -y git perl-core gcc httpd apr apr-util mod_perl \
            'perl(App::cpanminus)' make automake autoconf expat-devel which
            cpanm -v -n Class::Accessor::Fast
            cpanm -v -n Log::Log4perl
            cpanm -v -n Readonly
            cpanm -v -n List::Util
            cpanm -v -n Role::Tiny
            cpanm -v -n JSON
            cpanm -v -n XML::Simple
            cpanm -v -n JSON
            cpanm -v -n Tie::IxHash
            cpanm -v -n Number::Format
            cpanm -v -n Text::ASCIITable
            cpanm -v -n Text::CSV_XS
            cpanm -v -n IO::Scalar
            cpanm -v -n Crypt::CBC
            cpanm -v -n Crypt::DES
            cd /codebase
            ./bootstrap 
            ./configure --enable-rpm-build-mode
            make
            cd src/main/perl
            make test
